name: np3
channels:
  - conda-forge
  - bioconda
  - defaults
  - bokeh  
dependencies:
  - nodejs=15.2.0
  - r-base=3.6.3
  - r-inline=0.3.16
  - r-tibble=2.1.3
  - r-biocmanager=1.30.10
  - r-gtools=3.8.2
  - r-dplyr=0.8.3
  - r-purrr=0.3.2
  - bioconductor-xcms=3.6.1
  - r-readr=1.3.1
  - r-stringr=1.4.0
  - r-devtools=2.2.2
  - r-rcpparmadillo=0.9.700.2.0
  - r-rcdklibs=2.3
  - r-rcdk=3.5.0
  - r-rjson=0.2.20
  - r-squash=1.0.9
  - r-maldiquant=1.19.3
  - make=4.3
  - compilers
  - python=3.7
  - numpy=1.19.4
  - scipy=1.5.3
  - pandas=1.1.4
  - networkx=2.5
  - seaborn=0.11.1
  - matchms=0.9.2
  - bokeh=2.2.0
  - pybind11=2.7.1
  - streamlit=0.87.0
  - rdkit=2021.03.4
  - libgcrypt
  - pip
  - pip:
    - termplotlib==0.3.8
    - jinja2==3.0.3
    - altair==4.2.2

